version: '3.8'

services:
  clickhouse:
    image: yandex/clickhouse-server
    container_name: db-spectator-clickhouse
    volumes:
      - './databases/clickhouse/config/config.xml:/etc/clickhouse-server/config.xml'
      - './databases/clickhouse/data:/var/lib/clickhouse/'
      - './databases/clickhouse/clickhouse-files/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh'
    ports:
      - '${CLICKHOUSE_PORT}:${CLICKHOUSE_PORT}'
    environment:
      CLICKHOUSE_DB: '${CLICKHOUSE_DB}'
      CLICKHOUSE_USER: '${CLICKHOUSE_USER}'
      CLICKHOUSE_PASSWORD: '${CLICKHOUSE_PASSWORD}'
      CLICKHOUSE_TABLE: '${CLICKHOUSE_TABLE}'

  mongo:
    image: mongo
    container_name: db-spectator-mongo
    ports:
      - '${MONGODB_PORT}:${MONGODB_PORT}'
    environment:
      MONGO_INITDB_ROOT_USERNAME: '${MONGO_INITDB_ROOT_USERNAME}'
      MONGO_INITDB_ROOT_PASSWORD: '${MONGO_INITDB_ROOT_PASSWORD}'
      MONGO_INITDB_DATABASE: '${MONGO_INITDB_DATABASE}'
    volumes:
      - './databases/mongo/data:/data/db'
      - './databases/mongo/mongo-files:/var/lib/mongo-files'
      - './databases/mongo/config/mongod.conf:/etc/mongod.conf'
